"""super tenant + kb assignments

Revision ID: 33b444aa1de2
Revises: b48f70467b74
Create Date: 2026-07-08 07:21:46.424169

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '33b444aa1de2'
down_revision = 'b48f70467b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_assignments',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('kb_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('assigned_by', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_knowledge_base_assignments_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_knowledge_base_assignments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_assignments')),
    sa.UniqueConstraint('kb_id', 'tenant_id', name='uq_kb_assignment')
    )
    with op.batch_alter_table('knowledge_base_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_base_assignments_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_assignments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_tenant', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tenants_is_super_tenant'), ['is_super_tenant'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_is_super_tenant'))
        batch_op.drop_column('is_super_tenant')

    with op.batch_alter_table('knowledge_base_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_base_assignments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_assignments_kb_id'))

    op.drop_table('knowledge_base_assignments')
    # ### end Alembic commands ###
