"""initial schema

Revision ID: b48f70467b74
Revises: 
Create Date: 2026-07-06 13:38:12.236344

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b48f70467b74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=True),
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.CHAR(length=36), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_name', sa.String(length=200), nullable=False),
    sa.Column('tenant_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_tenant_code'), ['tenant_code'], unique=True)

    op.create_table('knowledge_bases',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('kb_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_knowledge_bases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases'))
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_bases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('chat_session_id', sa.CHAR(length=36), nullable=True),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost_usd', sa.Numeric(precision=16, scale=10), nullable=False),
    sa.Column('output_cost_usd', sa.Numeric(precision=16, scale=10), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=16, scale=10), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_usage_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_logs'))
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_chat_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('kb_id', sa.CHAR(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_status', sa.String(length=20), nullable=False),
    sa.Column('kmrag_document_id', sa.String(length=120), nullable=True),
    sa.Column('kmrag_request_id', sa.CHAR(length=36), nullable=True),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.CHAR(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_documents_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_upload_status'), ['upload_status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('chat_session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('answer_mode', sa.String(length=30), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retrieval_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_chat_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_chat_messages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('chat_session_knowledge_bases',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('chat_session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('kb_id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_chat_session_knowledge_bases_chat_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_chat_session_knowledge_bases_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_chat_session_knowledge_bases_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session_knowledge_bases')),
    sa.UniqueConstraint('chat_session_id', 'kb_id', name='uq_session_kb')
    )
    with op.batch_alter_table('chat_session_knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_knowledge_bases_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_session_knowledge_bases_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_session_knowledge_bases_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('chat_sources',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('message_id', sa.CHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('kb_id', sa.CHAR(length=36), nullable=True),
    sa.Column('document_id', sa.CHAR(length=36), nullable=True),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=120), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source_text_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_chat_sources_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_chat_sources_message_id_chat_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_chat_sources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sources'))
    )
    with op.batch_alter_table('chat_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sources_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sources_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sources_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sources_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sources_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sources_kb_id'))

    op.drop_table('chat_sources')
    with op.batch_alter_table('chat_session_knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_knowledge_bases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_session_knowledge_bases_kb_id'))
        batch_op.drop_index(batch_op.f('ix_chat_session_knowledge_bases_chat_session_id'))

    op.drop_table('chat_session_knowledge_bases')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_chat_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_upload_status'))
        batch_op.drop_index(batch_op.f('ix_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_documents_kb_id'))

    op.drop_table('documents')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_status'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_request_type'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_model_name'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_chat_session_id'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_status'))

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_tenant_code'))
        batch_op.drop_index(batch_op.f('ix_tenants_status'))

    op.drop_table('tenants')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
